@api = http://localhost:5000


//GET ALL CLASES
GET {{api}}/clases

###
// MATERIAS QUE DAN CLASES HOY O EN UN DIA DE LA SEMANA
GET {{api}}/clases/asignaturasByDay/Jueves


// DOCENTES QUE DAN CLASES HOY O EN UN DIA DE LA SEMANA
###
GET {{api}}/clases/docentesByDay/Jueves